icons_format = "{icon}"

[theme]
theme = "nord-dark"

[icons]
icons = "awesome4"

[[block]]
block = "net"

[[block]]
block = "temperature"

[[block]]
block = "cpu"
[[block.click]]
button = "left"
cmd = "kitty htop"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R')"
[[block.click]]
button = "left"
cmd = "kitty wtfutil"

[[block]]
block = "sound"
headphones_indicator = true